micronaut:
  application:
    name: metricsExercise
# TODO: uncomment this if you want a JDBC database running in docker/testcontainers.
# datasources:
#   default:
#     url: jdbc:tc:mysql:8.0:///test?TC_DAEMON=true
#     driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
#     username: test
#     password: test
#     schema-generate: CREATE
#     dialect: MYSQL
